title = "Consent Accelerator"
baseURL = "https://docs.snowplow.io/accelerators/consent/"

[params]
  description = "Enhanced Consent Plugin Accelerator"
  author = "Jack Keene, Agnes Kiss, Peter Perlepes"
  intercom=false

[markup.goldmark.renderer]
  unsafe = true
